import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import NavBar from "./NavBar";
import "./globals.css";

const tenorite = localFont({
  src: [
    {
      path: "../public/fonts/tenorite-reg.ttf",
      weight: "400",
    },
    {
      path: "../public/fonts/tenorite-bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-tenorite",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={tenorite.variable}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          <main className="p-5">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
